# --- Imagen base con Java y Python ---
FROM openjdk:17-slim

# --- Instalar Python, pip, curl y librerías de PyQt5 ---
RUN apt-get update && apt-get install -y \
    python3 python3-pip curl \
    libgl1 libglib2.0-0 libx11-6 libxext6 libxrender1 libxcb1 libxkbcommon-x11-0 && \
    rm -rf /var/lib/apt/lists/*

# --- Instalar Poetry ---
RUN curl -sSL https://install.python-poetry.org | python3 -

ENV QT_QPA_PLATFORM=offscreen
# --- Añadir Poetry al PATH ---
ENV PATH="/root/.local/bin:$PATH"

# --- Crear directorio de trabajo ---
WORKDIR /app

# --- Copiar proyecto completo ---
COPY . ParetoInvest/

WORKDIR /app/ParetoInvest

# --- Instalar dependencias Python con Poetry ---
RUN poetry install --no-root

# --- Añadir la raíz al PYTHONPATH para que los imports funcionen ---
ENV PYTHONPATH=/app

# --- Comando por defecto: ejecutar main.py ---
CMD ["poetry", "run", "python", "ParetoInvest/main.py"]
