name: Build ParetoInvest App (Windows)

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Poetry
        run: pip install poetry

      - name: Configure Poetry to create virtualenv inside project
        run: poetry config virtualenvs.in-project true
      
      - name: Install Poetry and dependencies
        run: |
          pip install poetry
          poetry config virtualenvs.in-project true
          poetry install --no-interaction --no-root

      - name: Install Qt dependencies
        run: sudo apt-get update && sudo apt-get install -y libegl1 libgl1-mesa-dev
          
      - name: Run tests (without GUI)
        run: |
          export QT_QPA_PLATFORM=offscreen          
          poetry run pytest ParetoInvest/tests -v
        env:
          PYTHONUNBUFFERED: 1

      - name: Build executable
        run: |
          poetry run pip install pyinstaller PyQt6 pandas numpy yfinance ib_insync asyncio
          poetry run pyinstaller --clean --onedir --noconfirm --windowed ParetoInvest/main.py --add-data "ParetoInvest/ui:ParetoInvest/ui" --add-data "ParetoInvest/models:ParetoInvest/models" --add-data "ParetoInvest/libraries:ParetoInvest/libraries" --hidden-import pandas --hidden-import numpy --hidden-import dateutil --hidden-import pytz --hidden-import requests --hidden-import yfinance --hidden-import ib_insync --hidden-import asyncio --hidden-import timeit --additional-hooks-dir=pyinstaller_hooks
 
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ParetoInvest_App_Ubuntu
          path: dist/main.exe
          