name: Build PyQt5 App (Windows)

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  build:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Poetry
        run: pip install poetry

      - name: Configure Poetry to create virtualenv inside project
        run: poetry config virtualenvs.in-project true
      
      # 👇 Instalar PyQt5 directamente (antes de Poetry)      
      - name: Preinstall PyQt5 wheel to avoid build from source
        run: |
          pip install --only-binary=:all: PyQt5==5.15.11 PyQt5-sip
      
      - name: Install Poetry and dependencies
        run: |
          pip install poetry
          poetry config virtualenvs.in-project true
          poetry install --no-interaction --no-root

      # Opcional: ejecutar tests unitarios sin GUI
      - name: Run tests (without GUI)
        run: poetry run pytest ParetoInvest/tests -v
        env:
          PYTHONUNBUFFERED: 1

      - name: Build executable
        run: |
          poetry run pip install pyinstaller PyQt5 pandas numpy yfinance ib_insync asyncio
          poetry run pyinstaller --clean --onedir --noconfirm --windowed ParetoInvest/main.py --add-data "ParetoInvest/ui:ParetoInvest/ui" --add-data "ParetoInvest/models:ParetoInvest/models" --add-data "ParetoInvest/libraries:ParetoInvest/libraries" --hidden-import pandas --hidden-import numpy --hidden-import dateutil --hidden-import pytz --hidden-import requests --hidden-import yfinance --hidden-import ib_insync --hidden-import asyncio --hidden-import timeit --additional-hooks-dir=pyinstaller_hooks
 
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: PyQt5App
          path: dist/main.exe
          